"""Builds the tool registry: name → Tool (schemas, risk tier, idempotent, handler)."""

from __future__ import annotations

from . import handlers
from .base import RiskTier, Tool
from .schemas import (
    ClaimHistoryArgs,
    ClaimHistoryResult,
    CommSendArgs,
    CommSendResult,
    CoverageCheckArgs,
    CoverageCheckResult,
    DocRequestArgs,
    DocRequestResult,
    DuplicateCheckArgs,
    DuplicateCheckResult,
    EscalateArgs,
    EscalateResult,
    FraudScanArgs,
    FraudScanResult,
    PaymentExecuteArgs,
    PaymentExecuteResult,
    PolicyLookupArgs,
    PolicyLookupResult,
    RepairCostArgs,
    RepairCostResult,
    ReserveSetArgs,
    ReserveSetResult,
)


def build_registry() -> dict[str, Tool]:
    tools: list[Tool] = [
        Tool(
            name="policy_lookup",
            description="Fetch the policy record from the policy-admin system (mock).",
            args_schema=PolicyLookupArgs,
            result_schema=PolicyLookupResult,
            risk_tier=RiskTier.T0,
            idempotent=True,
            handler=handlers.policy_lookup,
        ),
        Tool(
            name="coverage_check",
            description="Determine whether the loss is covered (rules-only stub in Phase 1).",
            args_schema=CoverageCheckArgs,
            result_schema=CoverageCheckResult,
            risk_tier=RiskTier.T0,
            idempotent=False,
            handler=handlers.coverage_check,
        ),
        Tool(
            name="repair_cost_estimator",
            description="Line-item repair estimate from a parts/labor table (mock).",
            args_schema=RepairCostArgs,
            result_schema=RepairCostResult,
            risk_tier=RiskTier.T0,
            idempotent=True,
            handler=handlers.repair_cost_estimator,
        ),
        Tool(
            name="reserve_set",
            description="Set/adjust the financial reserve (T1, idempotent via key).",
            args_schema=ReserveSetArgs,
            result_schema=ReserveSetResult,
            risk_tier=RiskTier.T1,
            idempotent=True,
            handler=handlers.reserve_set,
        ),
        Tool(
            name="payment_execute",
            description="Disburse settlement via mock ACH (T2; requires authorization).",
            args_schema=PaymentExecuteArgs,
            result_schema=PaymentExecuteResult,
            risk_tier=RiskTier.T2,
            idempotent=True,
            handler=handlers.payment_execute,
        ),
        Tool(
            name="customer_comm_send",
            description="Draft (T0) or send (T2) a templated claimant communication.",
            args_schema=CommSendArgs,
            result_schema=CommSendResult,
            risk_tier=RiskTier.T2,
            idempotent=False,
            handler=handlers.customer_comm_send,
        ),
        Tool(
            name="claim_history",
            description="Claimant's prior claims and 24-month count (mock).",
            args_schema=ClaimHistoryArgs,
            result_schema=ClaimHistoryResult,
            risk_tier=RiskTier.T0,
            idempotent=True,
            handler=handlers.claim_history,
        ),
        Tool(
            name="duplicate_claim_check",
            description="Exact (and, in Phase 3, semantic) duplicate-claim detection.",
            args_schema=DuplicateCheckArgs,
            result_schema=DuplicateCheckResult,
            risk_tier=RiskTier.T0,
            idempotent=True,
            handler=handlers.duplicate_claim_check,
        ),
        Tool(
            name="fraud_signal_scan",
            description="Hybrid fraud screen producing a score + itemized signals (rules-only v1).",
            args_schema=FraudScanArgs,
            result_schema=FraudScanResult,
            risk_tier=RiskTier.T0,
            idempotent=False,
            handler=handlers.fraud_signal_scan,
        ),
        Tool(
            name="document_request_create",
            description="Request specific documents; opens the W4 info-request loop (T1).",
            args_schema=DocRequestArgs,
            result_schema=DocRequestResult,
            risk_tier=RiskTier.T1,
            idempotent=False,
            handler=handlers.document_request_create,
        ),
        Tool(
            name="escalate_to_human",
            description="Create a human task with full context — the universal exit (T1).",
            args_schema=EscalateArgs,
            result_schema=EscalateResult,
            risk_tier=RiskTier.T1,
            idempotent=False,
            handler=handlers.escalate_to_human,
        ),
    ]
    return {t.name: t for t in tools}
